apiVersion: apps/v1
kind: Deployment
metadata:
  name: chembl-webservices-py3-deployment
  labels:
    app: chembl-webservices-py3-deployment
spec:
  selector:
    matchLabels:
      app: chembl-webservices-py3-template
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: chembl-webservices-py3-template
        tier: backend
    spec:
      containers:
      - name: chembl-webservices-py3-container
        securityContext:
          runAsUser: 2892 # UID for user cbl_adm
        envFrom:
          - configMapRef:
              name: chembl-webservices-py3-cm
        image: <DOCKER_IMAGE>:<VERSION>
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: chembl-webservices-py3-service
spec:
  selector:
    app: chembl-webservices-py3-deployment
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
